### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by SkiingIsFun123**
Updated readability of the README.md file

### CODE REVIEW

**Comment by badrinathvm** [comment]
Thank you @SkiingIsFun123 for checking out this repository and creating a PR appreciate a ton.

**Comment by Mbra771** [comment]
Hallo badrinathvm,
I realy like StepperView very much. But I have a little problem using it in my app. 
Instead of : 
`                let steps = [ Text("Cart").font(.caption),
                              Text("Delivery Address").font(.caption),
                              Text("Order Summary").font(.caption),
                              Text("Payment Method").font(.caption),
                              Text("Track").font(.caption)]`

I would like to generate the list for the steps.
Unfortunately that doesn't work as expected.

Here my try:
`    var steps  :  some View {
              ForEach(aktWorkout.uebung, id: \.self) {
                  Text("\($0)").font(.caption)
                  } // ForEach
              }`

It would be nice if you could give me a tip. 
Thanks, and greetings from Germany. :-)

**Comment by badrinathvm** [comment]
Thank you so much for checking out this library. Can you try below code and see if it works ?

var steps : AnyView { ForEach(aktWorkout.uebung, id: \.self) { Text("\($0)").font(.caption) } }.eraseTOAnyView()

Happy to help further if issue still exists.

**Comment by Mbra771** [comment]
Thank you so much for helping me. 
Unfortunately the error still exists.

I tryed :
` @Enviroment var steps : AnyView { ForEach(aktWorkout.uebung, id: \.self) { Text("\($0)").font(.caption) } }.eraseToAnyView()`

I then get the error:

`Cannot convert return expression of type 'ForEach<[String], String, Text>' to return type 'AnyView'`

If I have an array with only String . How can I create a 
var : steps 
from this that works with your library?

Once again many thanks for your help

**Comment by badrinathvm** [comment]
Please try below code 

`
struct ExampleView13: View {
    
    func getsteps(elements: [String]) -> [AnyView] {
        var cells = [AnyView]()
        for (_, element) in elements.enumerated() {
            cells.append(Text(element).eraseToAnyView())
        }
        return cells
    }
    
    // indications types commonn for both the modes
    @State var indicationTypes = [StepperIndicationType.custom(NumberedCircleView(text: "1")),
                            .custom(NumberedCircleView(text: "2")),
                            .custom(NumberedCircleView(text: "3")),
                            .custom(NumberedCircleView(text: "4"))]
    
    var body: some View {
        StepperView()
            .addSteps(getsteps(elements: ["Cart", "Delivery Address", "Summary", "Tracking"]))
            .indicators(self.indicationTypes)
            .stepIndicatorMode(StepperMode.horizontal)
            .spacing(50)
            .lineOptions(StepperLineOptions.custom(1, Colors.blue(.teal).rawValue))
            .padding(.top, 20)
    }
}`

**Comment by Mbra771** [comment]
It works now. :-)
Thank you very much for your support. 

I tried to buy you a coffee but I kept getting an error.
Can I buy you a coffee via PayPal?

**Comment by badrinathvm** [comment]
Glad it worked for you. Happy to help for any more items.

That’s so nice of you. Here’s the link to buy me a coffee

https://www.buymeacoffee.com/badrinathvm


Thanks,
Badarinath

**Pull request merged**
