### PR TITLE
[PR Request] - Removes default .black rendering for CircledIconView

### PR DESCRIPTION
**Pull request by acegreen**
The default was setting rending to template and color to .black.

## Description

Please include a summary of the change and which issue is fixed.

## Type of change

- [X] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] This change requires a documentation update

## How Has This Been Tested

Please let us know if you have tested your PR and if we need to reproduce the issues. Also, please let us know if we need any relevant information for running the tests.

NOT TESTED

## Test Configuration

N/A

## Checklist:

 For checklist items not applicable, mention NA in front of it with some comment if applicable.

 - [X] My code follows the style guidelines of this project
 - [X] I have performed a self-review of my own code
 - [X] Add comments to code particularly in hard-to-understand areas
 - [X] My changes generate no new warnings
 - [X] I have added tests that prove my fix is effective or that my feature works
 - [X] New and existing unit tests pass locally with my changes before pushing the pull request

### CODE REVIEW

**Review by badrinathvm — APPROVED** [review]
Thank you to much for contributing to StepperView. Changes looks good.

**Comment by acegreen** [comment]
@badrinathvm one minor thing I forgot was to `= nil` in the initializer. I hadn't setup my local version to test but now I did it so ill be able to test better.

**Comment by acegreen** [comment]
@badrinathvm also noticed my extension wasn't necessary as a `ifTrue` already exists

**Comment by badrinathvm** [comment]
Can you create a new PR to remove the unrequited extension

**Pull request merged**
